### ISSUE TITLE
Not-so-brief Comments

### ISSUE THREAD

**Issue by eugene-eeo** [kirkthaker/investopedia-trading-api#1]
Hi. I've found your library through your reddit post- I'd skip the formalities and dive right into the comments. Take note that these comments are valid for commit 8d6dbfd. Firstly you are using too many comments- I counted about 41 comments in a 135 line file. Comments are fine, don't get me wrong, but you should really take a look at your code and see if the intent behind it is obvious even without comments.

Secondly it feels as though we are writing C here- why do this:

```python
handle = login(_, _)
trade(handle, ...)
```

When we ~~can~~ should instead do this with a more OO way:

```python
client = login(_, _)
client.trade(...)
```

It has the additional benefit of not exposing too big an API surface- for example if one day you changed from `mechanize` to some other library your users wouldn't complain as much simply because you haven't explicitly returned a `Browser` object. However if you did then they would come to rely on it and ultimately write code that depends on it. **_In short, you want to hide the implementation and expose the interface._**

Thirdly please consider more intuitive variable names- `login(username, password)` suggests that it takes in a username, but in reality submits an email address? (See line 18). Also what you are having in the trade function is essentially an enum- there are a list of possible actions, from what I see in the README,

 - Buy (1)
 - Sell (2)

So you might want to consider either using the [enum](https://docs.python.org/3/library/enum.html) library in Python 3 or using the [backported enum module](https://pypi.python.org/pypi/enum34/) if you *have* to target Python 2.x. That way you can write:

```python
class Action(Enum):
    buy = 1
    sell = 2

client.trade("GOOG", Action.buy, 10)
```

Which gives you sort of a "type safety" if you write type checks in the `trade` method, and also reduces the chances of errors. After all, selling and buying shares is *quite* a big deal.

Also, in line 47: "This could probably be more elegant...". Please, make it more elegant. In it's current form it requires a LOT of brainpower to even try and parse what you are trying to express with the code. A slight deviation from the technical points but please try to follow the naming conventions- in Python classes are written in `CapitalisedCamelCase`, while functions, methods, and variables are written in `snake_case`.

In the getPortfolioStatus function you are returning what looks like an arbitrary tuple with all sorts of numbers inside. What you should be doing here is returning a [namedtuple](https://docs.python.org/2/library/collections.html#collections.namedtuple). That way the individual components that make up the portfolio can be easily and correctly accessed:

```
portfolio = client.get_portfolio_status()
portfolio.account_value
portfolio.cash_value
#etc
```

**Comment by kirkthaker** [comment]
Thanks for the feedback! I've made pretty much all of the fixes you've recommended. The only thing I've left is making getPortfolioStatus more elegant - I'll probably need to use a library like BeautifulSoup to do that, so I I need to read up on it first. Let me know what you think of the changes.

**Comment by eugene-eeo** [comment]
Very nicely done. Note that the namedtuple constructor is only meant to be created once- for example,

```python
Status = namedtuple('Status', '...')

class Account:
    def getPortfolioStatus(self):
        ...
        return Status(...)
```

You can also use keyword arguments when creating your Status object, for example

```python
Status(
    cash_value=something,
    ...
)
```

Just to make your code clearer; but it's optional.

**Comment by eugene-eeo** [comment]
I am on mobile so I'm sorry that I couldn't squash this into a single comment- is there a good reason to return True and False in the `Account.trade` method? Normally we'll just let exceptions be raised.

**Comment by kirkthaker** [comment]
Initially, I thought it would be useful to suppress any exceptions during trading (so that an error wouldn't bring the whole trading algorithm to a halt). Looking at it now, it's probably more sensible to let users do whatever they want with exceptions (instead of this class already suppressing it for them).
