### ISSUE TITLE
Account statement

### ISSUE THREAD

**Issue by ShikariShambhu** [kirkthaker/investopedia-trading-api#11]
Help pls.. 

> > > client = Account("abc@gmail.com","123")
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python2.7/dist-packages/investopedia.py", line 37, in **init**
> > >     br.select_form(nr=2)
> > >   File "/usr/local/lib/python2.7/dist-packages/mechanize/_mechanize.py", line 524, in select_form
> > >     raise FormNotFoundError("no form matching "+description)
> > > mechanize._mechanize.FormNotFoundError: no form matching nr 2

**Comment by paltryore** [comment]
Fixed in May 15, 2016 pull. #7
