### ISSUE TITLE
No status report when doing an action

### ISSUE THREAD

**Issue by josephernest** [kirkthaker/investopedia-trading-api#2]
When I do 

    client.trade("GOOG", Action.buy, 10)

I get no report of success / failure. It seems that it failed (because closed?)
How to have a status report?

**Comment by kirkthaker** [comment]
The trade function should return True if the trade was successful. Otherwise, it should return whatever error caused it to fail. What's your full code look like? Post it here so that we can see it. Also, remember that you have to login before you start making trades.

**Comment by kirkthaker** [comment]
Any luck so far with your error?
