### ISSUE TITLE
error get portfolio_status()

### ISSUE THREAD

**Issue by JoePython1** [kirkthaker/investopedia-trading-api#5]
Error getting status.

    >>> status = client.get_portfolio_status()
    Traceback (most recent call last):
     File "<stdin>", line 1, in <module>
     File "investopedia.py", line 64, in get_portfolio_status
     account_value = parsed_html.find('span', attrs={'id':acct_val_id}).text
     AttributeError: 'NoneType' object has no attribute 'text'

**Comment by kirkthaker** [comment]
This might be the result of a non-existent portfolio. Are you sure that you've both made an Investopedia account and joined a specific game (like the 2016 Stock Only Game, for example)?

**Comment by JoePython1** [comment]
I used facebook oauth. I changed it to a regular password and it is good now.
