### ISSUE TITLE
Intraday trading and data using this API?

### ISSUE THREAD

**Issue by potholiday** [kirkthaker/investopedia-trading-api#8]
Can we fetch intra day data for intra day simulated trading? Does this API fetches intraday/EOD data or we have to use our own data feed? Where we can find the documentation for this API?

**Comment by kirkthaker** [comment]
This is simply a wrapper that allows for automated trading via Investopedia's simulator platform. Where you get the data that informs your algorithm's decision making is up to you (you have to find your own data feed). 

I wrote another script that gets price and volume data from Google Finance (https://github.com/kirkthaker/stock-data-wrapper) but I think there are other (more sophisticated) data apis for finance.
