### ISSUE TITLE
How to install investopedia-trading-api in ubuntu

### ISSUE THREAD

**Issue by potholiday** [kirkthaker/investopedia-trading-api#9]
I cant install investopedia-trading-api in my ubuntu system. I have downloaded the zip file and unzipped it and used this code to install the api

` sudo python setup.py install
`
and it cerrated a build folder in current directory and this is the result

```
running install
running build
running build_py
package init file 'investopedia-trading-api/__init__.py' not found (or not a regular file)
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/investopedia-trading-api
copying investopedia-trading-api/investopedia.py -> build/lib.linux-x86_64-2.7/investopedia-trading-api
package init file 'investopedia-trading-api/__init__.py' not found (or not a regular file)
running install_lib
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/investopedia_trading_api-1.0.egg-info
Writing /usr/local/lib/python2.7/dist-packages/investopedia_trading_api-1.0.egg-info

```

but when it tried to import investopedia in python its giving me this result

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named investopedia

```
any idea what is happening here?

**Comment by kirkthaker** [comment]
After a bit of searching, it seems that the issue has to do with the name...you can't have hyphens in a python module's name. The problem could be something else, but this seems to be the most likely explanation. As a possible fix you could simply extract investopedia.py by itself and include it in the directory of whatever trading app you're writing. :(

**Comment by potholiday** [comment]
thanks for the info :+1:
